//! Simulation-backed market data: option chains and series generated by
//! driving a random walk over a seed chain or series.
//!
//! This is the only place where market data depends on the simulation
//! engine (ADR-0003). It is gated by the `synthetic` feature (on by
//! default), so `default-features = false` leaves a market surface that names
//! no simulation type. The generators live in the facade until the
//! simulation layer is its own crate; M5 then moves them into
//! `optionstratlib-market` behind its own `synthetic` feature (#537), with
//! the facade routing in #541.
//!
//! A generator's simulation failure reaches the caller as
//! `ChainError::Generator`, whose source downcasts to `SimulationError`.

/// Chain generation over a random walk.
mod chains;

/// Series generation over a random walk.
mod series;

pub use chains::generator_optionchain;
pub use series::generator_optionseries;

use crate::error::{ChainError, SimulationError};

/// A simulation failure inside a chain or series generator travels as
/// [`ChainError::Generator`], keeping the `SimulationError` as its
/// downcastable source. It lives here, the one module that sits above both
/// market and simulation, so neither layer names the other (#524).
impl From<SimulationError> for ChainError {
    #[inline]
    fn from(err: SimulationError) -> Self {
        ChainError::generator(err)
    }
}
