//! Simulation-backed market data: option chains and series generated by
//! driving a random walk over a seed chain or series.
//!
//! This is the only place where market data depends on the simulation
//! engine (ADR-0003). It is gated by the `synthetic` feature (on by
//! default), so `default-features = false` leaves a market surface that names
//! no simulation type. The generators live in the facade until the
//! simulation layer is its own crate; M5 then moves them into
//! `optionstratlib-market` behind its own `synthetic` feature (#537), with
//! the facade routing in #541.
//!
//! A generator's simulation failure reaches the caller as
//! `ChainError::Generator`, whose source downcasts to `SimulationError`.

/// Chain generation over a random walk.
mod chains;

/// Series generation over a random walk.
mod series;

pub use chains::generator_optionchain;
pub use series::generator_optionseries;

/// Deterministic walkers shared by the generator tests.
#[cfg(test)]
mod walk_test_support;

use crate::error::{ChainError, SimulationError};

/// The error a generator step carries through the walk driver.
///
/// `walk_steps_par` raises its own failures as `E::from(SimulationError)`.
/// `ChainError` and `SimulationError` are defined in two other crates
/// (`optionstratlib-market`, `optionstratlib-simulation`), so the facade
/// cannot implement that conversion on `ChainError` itself; it implements it
/// on this private carrier instead, and the generators unwrap it on return.
/// A simulation failure therefore still reaches the caller as
/// [`ChainError::Generator`] with the `SimulationError` as its downcastable
/// source, and a step's own `ChainError` comes back unchanged (#536).
#[derive(Debug)]
struct GeneratorFailure(ChainError);

impl GeneratorFailure {
    /// The `ChainError` the generator returns.
    #[inline]
    fn into_inner(self) -> ChainError {
        self.0
    }
}

impl From<SimulationError> for GeneratorFailure {
    #[cold]
    #[inline(never)]
    fn from(err: SimulationError) -> Self {
        GeneratorFailure(ChainError::generator(err))
    }
}
