#!/usr/bin/env python3
"""Pin the dependency graph of the minimal market surface and of `synthetic`.

Roadmap M1-15 asks for cargo-tree fixtures that assert the expected
difference between the market surface without `synthetic` and with it. Each
surface gets its own fixture holding the whole graph, so a change that adds,
removes or re-parents a dependency shows up even when it lands on both
surfaces at once; the difference between the two is derived from them and
printed. While `optionstratlib` is a single crate that difference is empty,
and that *is* the assertion for it: `synthetic` gates source, not crates, so
the first crate the feature pulls in shows up as a fixture diff. When the
workspace split lands (#525, #537) the same fixtures carry the real
difference without the check having to change.

Normalisation, and what it costs:

* `--target all` resolves every target's dependencies, so the fixture is the
  same on macOS, Linux and Windows. Without it the graph is the host's and a
  developer machine and CI disagree.
* Nodes are package names without versions, and the graph is stored as a
  sorted `parent -> child` edge list. `Cargo.lock` is not committed, so a
  version recorded here would be whatever the resolver picked that day and
  an unrelated upstream patch release would fail CI for every contributor.
  The cost is real: a version bump, and two versions of one package
  collapsing into one node, are invisible to this check. Pinning those needs
  a committed lockfile, which is a packaging decision, tracked separately.

Usage:
    check_feature_trees.py            compare against the fixtures
    check_feature_trees.py --update   rewrite the fixtures
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FIXTURES = ROOT / "tests" / "fixtures" / "feature-trees"

# name -> the cargo feature flags that select the surface.
SURFACES = {
    "minimal": ["--no-default-features"],
    "synthetic": ["--no-default-features", "--features", "synthetic"],
}

HEADER = """# Dependency graph of the `{surface}` market surface, as a sorted
# `parent -> child` edge list over package names, resolved with
# `cargo tree --target all -e no-dev`. Generated by
# `make feature-trees-update`; see scripts/check_feature_trees.py for why
# versions are not recorded.
"""


def edges(flags: list[str]) -> list[str]:
    """The `parent -> child` edges `cargo tree` resolves for one surface."""
    result = subprocess.run(
        [
            "cargo", "tree", "--target", "all", "-e", "no-dev",
            "--prefix", "depth", "--format", "{p}", *flags,
        ],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        print(result.stderr, file=sys.stderr)
        raise SystemExit(f"cargo tree failed for {' '.join(flags)}")

    found: set[str] = set()
    stack: list[str] = []
    for line in result.stdout.splitlines():
        line = line.strip()
        if not line or not line[0].isdigit():
            continue
        digits = len(line) - len(line.lstrip("0123456789"))
        depth = int(line[:digits])
        # "name v1.2.3 (proc-macro)" / "name v1.2.3 (*)" -> "name"
        name = line[digits:].split()[0]
        del stack[depth:]
        stack.append(name)
        if depth:
            found.add(f"{stack[depth - 1]} -> {name}")
    return sorted(found)


def render(surface: str, graph: list[str]) -> str:
    return HEADER.format(surface=surface) + "\n".join(graph) + "\n"


def main() -> int:
    update = "--update" in sys.argv
    FIXTURES.mkdir(parents=True, exist_ok=True)
    graphs = {name: edges(flags) for name, flags in SURFACES.items()}

    failures = 0
    for surface, graph in graphs.items():
        path = FIXTURES / f"{surface}.txt"
        rendered = render(surface, graph)
        if update:
            path.write_text(rendered)
            print(f"updated {path.relative_to(ROOT)} ({len(graph)} edges)")
            continue
        if not path.exists():
            print(f"missing fixture {path.relative_to(ROOT)}; run 'make feature-trees-update'", file=sys.stderr)
            failures += 1
            continue
        if path.read_text() != rendered:
            expected = set(path.read_text().splitlines())
            print(f"the {surface!r} surface's dependency graph drifted:", file=sys.stderr)
            for line in sorted(set(graph) - expected):
                print(f"  + {line}", file=sys.stderr)
            for line in sorted(expected - set(graph) - {""} ):
                if not line.startswith("#"):
                    print(f"  - {line}", file=sys.stderr)
            print("If this is intentional, run 'make feature-trees-update' and commit the diff.", file=sys.stderr)
            failures += 1

    if update:
        return 0
    if failures:
        return 1

    added = sorted(set(graphs["synthetic"]) - set(graphs["minimal"]))
    removed = sorted(set(graphs["minimal"]) - set(graphs["synthetic"]))
    detail = "no edge (the feature gates source, not crates)"
    if added or removed:
        detail = f"{len(added)} edge(s) added, {len(removed)} removed: " + ", ".join(added + removed)
    print(
        f"OK: both market dependency graphs match their fixtures "
        f"({len(graphs['minimal'])} edges); `synthetic` changes {detail}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
