#!/usr/bin/env python3
"""Pin the dependency graph of the minimal market surface and of `synthetic`.

Roadmap M1-15 asks for cargo-tree fixtures that assert the expected
difference between the market surface without `synthetic` and with it. Each
surface gets its own fixture holding the whole graph, so a change that adds,
removes or re-parents a dependency shows up even when it lands on both
surfaces at once; the difference between the two is derived from them and
printed. While `optionstratlib` is a single crate that difference is empty,
and that *is* the assertion for it: `synthetic` gates source, not crates, so
the first crate the feature pulls in shows up as a fixture diff. When the
workspace split lands (#525, #537) the same fixtures carry the real
difference without the check having to change.

Normalisation, and what it costs:

* `--target all` resolves every target's dependencies, so the fixture is the
  same on macOS, Linux and Windows. Without it the graph is the host's and a
  developer machine and CI disagree.
* The graph is stored as a sorted `parent -> child` edge list plus one
  `package [features]` line per package, so a dependency that `synthetic`
  promotes from transitive to direct is a new edge, and a feature it turns on
  for a package both surfaces already share is a changed feature line. Either
  one fails the check.
* Nodes are package names without versions. `Cargo.lock` is not committed, so
  a version recorded here would be whatever the resolver picked that day and
  an unrelated upstream patch release would fail CI for every contributor.
  The cost is real: a version bump, and two versions of one package
  collapsing into one node, are invisible to this check. Pinning those needs
  a committed lockfile, which is a packaging decision, tracked in #616.

Usage:
    check_feature_trees.py            compare against the fixtures
    check_feature_trees.py --update   rewrite the fixtures
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# CI sets `CARGO_TERM_COLOR=always`, so `--color never` alone is not enough on
# every cargo version; the output is stripped as well, or a coloured `(*)`
# marker would be read as a package's feature list.
ANSI_RE = re.compile(r"\x1b\[[0-9;]*m")
FIXTURES = ROOT / "tests" / "fixtures" / "feature-trees"

# name -> the cargo feature flags that select the surface.
SURFACES = {
    "minimal": ["--no-default-features"],
    "synthetic": ["--no-default-features", "--features", "synthetic"],
}

HEADER = """# Dependency graph of the `{surface}` market surface, resolved with
# `cargo tree --target all -e no-dev`: a sorted `parent -> child` edge list
# over package names, then the features enabled on each package. Generated by
# `make feature-trees-update`; see scripts/check_feature_trees.py for why
# versions are not recorded.
"""


def edges(flags: list[str]) -> list[str]:
    """The edges and per-package features `cargo tree` resolves for a surface."""
    result = subprocess.run(
        [
            "cargo", "tree", "--color", "never", "--target", "all",
            "-e", "no-dev", "--prefix", "depth", "--format", "{p} {f}", *flags,
        ],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        print(result.stderr, file=sys.stderr)
        raise SystemExit(f"cargo tree failed for {' '.join(flags)}")

    found: set[str] = set()
    features: dict[str, set[str]] = {}
    stack: list[str] = []
    for line in ANSI_RE.sub("", result.stdout).splitlines():
        line = line.rstrip()
        if not line or not line[0].isdigit():
            continue
        digits = len(line) - len(line.lstrip("0123456789"))
        depth = int(line[:digits])
        # `{p} {f}` gives "name v1.2.3 [(...)] [feat,feat]", where the
        # parenthesised field is a local path, `(proc-macro)` or `(*)` for an
        # already-shown subtree. Those are dropped, along with the version
        # (see the module docstring); whatever is left after the version is
        # the feature list. Dropping the path matters: for the root package
        # it is this checkout's absolute path.
        fields = [f for f in line[digits:].split() if not f.startswith("(")]
        name = fields[0]
        feats: set[str] = set()
        if len(fields) > 2:
            feats = {f for f in fields[2].split(",") if f}
        del stack[depth:]
        stack.append(name)
        if depth:
            found.add(f"{stack[depth - 1]} -> {name}")
        features.setdefault(name, set()).update(feats)
    graph = sorted(found)
    graph.append("")
    graph.extend(
        f"{name} [{','.join(sorted(feats))}]" for name, feats in sorted(features.items())
    )
    return graph


def render(surface: str, graph: list[str]) -> str:
    return HEADER.format(surface=surface) + "\n".join(graph) + "\n"


def main() -> int:
    update = "--update" in sys.argv
    FIXTURES.mkdir(parents=True, exist_ok=True)
    graphs = {name: edges(flags) for name, flags in SURFACES.items()}

    failures = 0
    for surface, graph in graphs.items():
        path = FIXTURES / f"{surface}.txt"
        rendered = render(surface, graph)
        if update:
            path.write_text(rendered)
            print(f"updated {path.relative_to(ROOT)} ({len(graph)} lines)")
            continue
        if not path.exists():
            print(f"missing fixture {path.relative_to(ROOT)}; run 'make feature-trees-update'", file=sys.stderr)
            failures += 1
            continue
        if path.read_text() != rendered:
            expected = set(path.read_text().splitlines())
            print(f"the {surface!r} surface's dependency graph drifted:", file=sys.stderr)
            for line in sorted(set(graph) - expected):
                print(f"  + {line}", file=sys.stderr)
            for line in sorted(expected - set(graph) - {""} ):
                if not line.startswith("#"):
                    print(f"  - {line}", file=sys.stderr)
            print("If this is intentional, run 'make feature-trees-update' and commit the diff.", file=sys.stderr)
            failures += 1

    if update:
        return 0
    if failures:
        return 1

    added = sorted(set(graphs["synthetic"]) - set(graphs["minimal"]))
    removed = sorted(set(graphs["minimal"]) - set(graphs["synthetic"]))
    detail = "nothing (the feature gates source, not crates)"
    if added or removed:
        detail = f"{len(added)} line(s) added, {len(removed)} removed: " + ", ".join(added + removed)
    print(
        f"OK: both market dependency graphs match their fixtures "
        f"({len(graphs['minimal'])} lines); `synthetic` changes {detail}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
